import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
import {validateSave} from '../src/save.js';
const root=new URL('../',import.meta.url),artifacts=new URL('../test-results/',import.meta.url),port=4174,url=`http://localhost:${port}/?test=1`;
await mkdir(artifacts,{recursive:true});
const server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,WILDWOOD_PORT:String(port)},windowsHide:true,stdio:'pipe'});
let serverLog='';server.stdout.on('data',s=>serverLog+=s);server.stderr.on('data',s=>serverLog+=s);
let browser,page;const errors=[],results=[];
const log=(name,detail={})=>{results.push({name,...detail});console.log(`PASS ${name} ${Object.keys(detail).length?JSON.stringify(detail):''}`);};
const state=()=>page.evaluate(()=>({screen:__wildwood.screen,pos:{...__wildwood.player.pos},health:__wildwood.player.health,time:__wildwood.time,selected:__wildwood.inventory.selected,slots:__wildwood.inventory.serialize(),fps:__wildwood.fps,meshes:__wildwood.worldRenderer.meshes.size,chunks:__wildwood.world.chunks.size,queue:__wildwood.world.queue.length,draws:__wildwood.renderer.info.render.calls,triangles:__wildwood.renderer.info.render.triangles}));
const waitScreen=screen=>page.waitForFunction(s=>window.__wildwood?.screen===s,screen,{timeout:90000});
const screenshot=name=>page.screenshot({path:new URL(name+'.png',artifacts).pathname.replace(/^\/([A-Z]:)/,'$1'),timeout:30000});
try {
  for(let i=0;i<100;i++){try{if((await fetch(`http://127.0.0.1:${port}`)).ok)break;}catch{}if(i===99)throw new Error(`Server did not start: ${serverLog}`);await delay(100);}
  browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-swiftshader'],timeout:60000});
  const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,acceptDownloads:true});
  await context.tracing.start({screenshots:true,snapshots:true});
  page=await context.newPage();page.setDefaultTimeout(20000);
  page.on('pageerror',e=>{errors.push(e.stack||e.message);console.error('PAGE ERROR',e.message);});
  page.on('console',msg=>{if(msg.type()==='error'){errors.push(msg.text());console.error('CONSOLE ERROR',msg.text());}});
  await page.goto(url);await page.waitForFunction(()=>!!window.__wildwood,{timeout:60000});
  await page.waitForFunction(()=>__wildwood.worldRenderer.meshes.size>=45,{timeout:90000});await delay(800);
  assert.equal(await page.title(),'Wildwood · A voxel wilderness');await screenshot('01-title');log('production launch and title panorama',await state());
  await page.click('[data-action="new"]');await page.fill('#world-name','Browser Regression');await page.click('[data-action="create"]');await waitScreen('ready');await page.click('[data-action="enter"]');await waitScreen('playing');
  await page.waitForFunction(()=>document.pointerLockElement===document.querySelector('#game'));await delay(700);
  log('world creation and real pointer lock');await screenshot('02-gameplay');
  const before=await state();await page.keyboard.down('KeyW');await delay(1100);await page.keyboard.up('KeyW');const after=await state();assert.ok(Math.hypot(after.pos.x-before.pos.x,after.pos.z-before.pos.z)>.5,'WASD did not move player');
  const yaw=await page.evaluate(()=>__wildwood.player.yaw);await page.mouse.move(780,420);await delay(150);assert.notEqual(await page.evaluate(()=>__wildwood.player.yaw),yaw);log('keyboard movement and mouse look');
  await page.keyboard.press('Escape');await waitScreen('pause');const paused=await state();await delay(450);assert.equal((await state()).time,paused.time);log('pause freezes simulation');
  await page.click('#overlay [data-action="settings"]');await page.locator('[data-setting="radius"]').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await page.locator('[data-setting="fov"]').focus();await page.keyboard.press('Home');for(let i=0;i<22;i++)await page.keyboard.press('ArrowRight');await page.locator('[data-setting="showFps"]').check();await page.click('[data-action="back"]');await page.click('[data-action="resume"]');await waitScreen('playing');assert.equal(await page.evaluate(()=>__wildwood.settings.radius),3);log('settings apply and persist');
  // A reproducible elevated fixture isolates collision and block interactions
  // from randomly placed trees. Interactions below use real mouse/keyboard input.
  await page.evaluate(()=>{
    const g=__wildwood;g.mobs.list.slice().forEach(m=>g.mobs.remove(m));g.mobs.timer=999;
    for(let x=0;x<16;x++)for(let z=0;z<16;z++){g.world.setBlock(x,50,z,3);for(let y=51;y<58;y++)if(g.world.getBlock(x,y,z))g.world.setBlock(x,y,z,0);}
    g.player.safe(g.world,{x:5.5,y:51.01,z:8.5});g.player.yaw=0;g.player.pitch=0;g.player.health=20;g.player.vel={x:0,y:0,z:0};g.world.setBlock(5,52,5,2);g.select(0);
  });
  await delay(250);const earth=await page.evaluate(()=>__wildwood.inventory.count(2));await page.mouse.down({button:'left'});await delay(1050);await page.mouse.up({button:'left'});assert.equal(await page.evaluate(()=>__wildwood.world.getBlock(5,52,5)),0);assert.equal(await page.evaluate(()=>__wildwood.inventory.count(2)),earth+1);log('hold-to-mine, block removal and item pickup');
  await page.evaluate(()=>{__wildwood.world.setBlock(5,52,4,3);});await page.keyboard.press('Digit3');await delay(200);const plank=await page.evaluate(()=>__wildwood.inventory.count(7));await page.mouse.click(780,420,{button:'right'});await delay(200);assert.equal(await page.evaluate(()=>__wildwood.world.getBlock(5,52,5)),7);assert.equal(await page.evaluate(()=>__wildwood.inventory.count(7)),plank-1);log('right-click block placement and hotbar consumption');
  // Switching between blocks and tools also exercises GPU material disposal.
  for(const key of ['Digit5','Digit7','Digit1','Digit3']){await page.keyboard.press(key);await delay(100);}
  await page.mouse.down({button:'left'});await delay(1100);await page.mouse.up({button:'left'});assert.equal(await page.evaluate(()=>__wildwood.world.getBlock(5,52,5)),0);assert.equal(await page.evaluate(()=>__wildwood.world.getBlock(5,52,4)),3);log('mining with held building blocks and enforcing tool requirements');
  await page.keyboard.press('KeyE');await waitScreen('inventory');const invBefore=await state();await page.click('[data-recipe="planks"]');const invAfter=await state();assert.equal(invAfter.slots[3].count,invBefore.slots[3].count-1);assert.equal(invAfter.slots[2].count,invBefore.slots[2].count+4);assert.ok(await page.locator('[data-recipe="stone-pick"]').isDisabled());
  await page.evaluate(()=>{const g=__wildwood;g.world.setBlock(6,51,8,14);g.inventory.add(8,3);g.ui.renderInventory();});await page.click('[data-recipe="stone-pick"]');assert.equal(await page.evaluate(()=>__wildwood.inventory.count(106)),1);await screenshot('03-backpack-crafting');log('crafting consumes resources and enforces nearby workbench');
  const toolSlot=await page.evaluate(()=>__wildwood.inventory.slots.findIndex(s=>s?.id===106));await page.click(`#overlay [data-slot="${toolSlot}"]`);await page.click('#overlay [data-slot="6"]');assert.equal(await page.evaluate(()=>__wildwood.inventory.slots[6].id),106);log('backpack slot swapping');
  await page.click('#overlay [data-slot="6"]');await page.keyboard.down('ShiftLeft');await page.click('#overlay [data-slot="6"]');await page.keyboard.up('ShiftLeft');assert.equal(await page.evaluate(()=>__wildwood.inventory.slots[6]),null);assert.equal(await page.evaluate(()=>__wildwood.ui.picked),null);assert.equal(await page.evaluate(()=>__wildwood.inventory.count(106)),1);log('shift-transfer safely clears an already selected slot');
  await page.keyboard.press('KeyE');await waitScreen('playing');await delay(200);
  // A wall taller than the jump arc must stop sprinting and auto-jumping.
  await page.evaluate(()=>{const g=__wildwood;for(let x=3;x<=7;x++)for(let y=51;y<=55;y++)g.world.setBlock(x,y,5,3);g.player.safe(g.world,{x:5.5,y:51.001,z:8.5});g.player.yaw=0;g.player.pitch=0;});
  await page.keyboard.down('KeyW');await page.keyboard.down('ShiftLeft');await delay(1300);await page.keyboard.up('KeyW');await page.keyboard.up('ShiftLeft');assert.ok((await state()).pos.z>=6.289);log('solid voxel collision prevents wall penetration');
  await page.evaluate(()=>{const g=__wildwood;g.player.safe(g.world,{x:10.5,y:51.001,z:10.5});g.settings.autoJump=false;});await delay(250);const ground=(await state()).pos.y;await page.keyboard.down('Space');await delay(200);await page.keyboard.up('Space');assert.ok((await state()).pos.y>ground+.6);await delay(900);assert.ok(Math.abs((await state()).pos.y-51)<.01);log('jump, gravity and grounded landing');
  await page.evaluate(()=>{const g=__wildwood;g.player.safe(g.world,{x:10.5,y:58,z:10.5});g.player.health=20;g.player.invulnerable=0;});await delay(1400);assert.ok((await state()).health<20);await page.keyboard.press('Digit6');const foodBefore=await page.evaluate(()=>__wildwood.inventory.count(104)),healthBefore=(await state()).health;await page.mouse.click(780,420,{button:'right'});await delay(200);assert.ok((await state()).health>healthBefore);assert.equal(await page.evaluate(()=>__wildwood.inventory.count(104)),foodBefore-1);log('fall damage and eating to restore health');
  await page.evaluate(()=>{const g=__wildwood;for(let x=9;x<13;x++)for(let z=8;z<12;z++)for(let y=51;y<55;y++)g.world.setBlock(x,y,z,13);g.player.safe(g.world,{x:10.5,y:51.01,z:10.5});g.player.vel={x:0,y:0,z:0};});await delay(500);assert.ok(await page.evaluate(()=>__wildwood.player.underwater));await page.keyboard.down('Space');await delay(1400);await page.keyboard.up('Space');assert.ok((await state()).pos.y>54);log('water detection, air meter and swimming');
  await page.evaluate(()=>{const g=__wildwood;for(let x=9;x<13;x++)for(let z=8;z<12;z++)for(let y=51;y<55;y++)g.world.setBlock(x,y,z,0);g.player.safe(g.world,{x:10.5,y:51.01,z:10.5});g.player.yaw=0;g.player.pitch=-.04;g.player.health=20;g.player.invulnerable=0;g.time=720*.82;g.inventory.slots[0]={id:108,count:1};g.inventory.revision++;g.select(0);g.mobs.spawn('hollow',{x:10.5,y:51.01,z:9.3});});await delay(950);assert.ok((await state()).health<20);assert.ok(await page.evaluate(()=>__wildwood.atmosphere.night));
  for(let i=0;i<5;i++){await page.mouse.click(780,420);await delay(450);}assert.equal(await page.evaluate(()=>__wildwood.mobs.list.filter(m=>m.type==='hollow').length),0);assert.ok(await page.evaluate(()=>__wildwood.inventory.count(101)>=2));log('night cycle, hostile pursuit, health damage and sword combat');
  await page.evaluate(()=>{const g=__wildwood;g.mobs.spawn('sheep',{x:12.5,y:51.01,z:11.5});});const sheepPos=await page.evaluate(()=>({...__wildwood.mobs.list.find(m=>m.type==='sheep').pos}));await delay(700);assert.ok(await page.evaluate(()=>__wildwood.mobs.list.some(m=>m.type==='sheep')));log('passive sheep simulate and animate');
  const packBeforeDeath=await page.evaluate(()=>__wildwood.inventory.serialize());await page.evaluate(()=>{const g=__wildwood;g.player.invulnerable=0;g.player.damage(20,g,'Regression: fatal damage.');});await waitScreen('dead');await page.click('[data-action="respawn"]');await waitScreen('playing');assert.equal((await state()).health,20);assert.deepEqual(await page.evaluate(()=>__wildwood.inventory.serialize()),packBeforeDeath);log('death and safe respawn retain the backpack');
  await page.evaluate(()=>{const g=__wildwood;g.saveTimer=29.9;g.progress.autosaveProbe=true;});await delay(250);assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('wildwood.world.v1')).progress.autosaveProbe));log('automatic saving commits progress');
  await page.keyboard.press('Escape');await waitScreen('pause');await page.click('[data-action="save"]');const snapshot=await page.evaluate(()=>__wildwood.snapshot());
  const downloadPromise=page.waitForEvent('download');await page.click('[data-action="export"]');const download=await downloadPromise;await download.saveAs(new URL('regression-export.wildwood.json',artifacts).pathname.replace(/^\/([A-Z]:)/,'$1'));validateSave(snapshot);log('manual save and downloadable world export',{editedBlocks:snapshot.edits.reduce((a,[,e])=>a+e.length,0)});
  await page.reload();await page.waitForFunction(()=>!!window.__wildwood);assert.ok(await page.locator('[data-action="continue"]').isVisible());await page.click('[data-action="continue"]');await waitScreen('ready');assert.equal(await page.evaluate(()=>__wildwood.world.getBlock(5,52,5)),3);assert.deepEqual(await page.evaluate(()=>__wildwood.inventory.serialize()),snapshot.inventory);assert.equal(await page.evaluate(()=>__wildwood.player.health),snapshot.player.health);assert.equal(await page.evaluate(()=>__wildwood.time),snapshot.time);log('reload restores edited terrain, inventory, health, clock and saved creatures');
  await page.click('[data-action="enter"]');await waitScreen('playing');await page.evaluate(()=>{const g=__wildwood;g.player.safe(g.world,{x:250.5,y:g.world.getSurface(250,0)+.01,z:.5});g.world.plan(g.player.pos.x,g.player.pos.z,g.settings.radius);});await page.waitForFunction(()=>__wildwood.world.queue.length===0&&__wildwood.worldRenderer.pending.size===0&&__wildwood.worldRenderer.meshes.size>=40,{timeout:90000});assert.ok((await state()).chunks<=121);log('chunk streaming, worker meshing and bounded unloaded-world memory',await state());
  await page.keyboard.press('Escape');await waitScreen('pause');await page.click('[data-action="title"]');await page.locator('#import-file').setInputFiles({name:'invalid.wildwood.json',mimeType:'application/json',buffer:Buffer.from('{bad json')});await delay(200);assert.ok((await page.textContent('#toast')).startsWith('Could not import:'));await page.locator('#import-file').setInputFiles({name:'roundtrip.wildwood.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(snapshot))});await waitScreen('ready');assert.deepEqual(await page.evaluate(()=>__wildwood.inventory.serialize()),snapshot.inventory);assert.equal(await page.evaluate(()=>__wildwood.world.getBlock(5,52,5)),3);log('import rejects corrupt files and restores an exported world');
  await page.click('[data-action="enter"]');await waitScreen('playing');await page.keyboard.press('Escape');await waitScreen('pause');await page.click('[data-action="title"]');await page.click('[data-action="new"]');await page.fill('#world-name','Creative Meadow');await page.check('input[value="creative"]');await page.click('[data-action="create"]');await waitScreen('ready');await page.click('[data-action="enter"]');await waitScreen('playing');await page.keyboard.press('KeyF');assert.ok(await page.evaluate(()=>__wildwood.player.flying));const flyBefore=(await state()).pos.y;await page.keyboard.down('Space');await delay(800);await page.keyboard.up('Space');assert.ok((await state()).pos.y>flyBefore+3);await page.evaluate(()=>{const g=__wildwood;g.player.invulnerable=0;g.player.damage(100,g);});assert.equal((await state()).health,20);
  await page.keyboard.press('KeyE');await waitScreen('inventory');await page.click('[data-palette="17"]');assert.deepEqual(await page.evaluate(()=>__wildwood.inventory.held),{id:17,count:64});await page.keyboard.press('KeyE');await waitScreen('playing');log('creative flight, invulnerability and unlimited block palette');
  await page.evaluate(()=>{const g=__wildwood;g.player.yaw=.45;g.player.pitch=-.25;g.settings.showFps=false;g.player.flying=true;g.time=720*.36;});await delay(1200);await screenshot('04-creative-overlook');
  await page.evaluate(()=>{const g=__wildwood;g.time=720*.83;const p=g.player.pos,x=Math.floor(p.x),z=Math.floor(p.z),y=g.world.getSurface(x,z);g.world.setBlock(x,y,z,15);g.player.safe(g.world,{x:x+3.5,y:y+.01,z:z+4.5});g.player.yaw=.63;g.player.pitch=-.12;g.lanternTimer=0;});await delay(800);await screenshot('05-night');
  assert.equal(errors.length,0,`Browser errors:\n${errors.join('\n')}`);log('no uncaught JavaScript, shader, worker or asset errors');
  await context.tracing.stop({path:new URL('playwright-trace.zip',artifacts).pathname.replace(/^\/([A-Z]:)/,'$1')});
  await writeFile(new URL('browser-report.json',artifacts),JSON.stringify({passed:results.length,results,errors,completedAt:new Date().toISOString()},null,2));console.log(`\nAll ${results.length} browser checks passed. Screenshots and trace saved in test-results.`);
} catch(error) {
  console.error(error);if(page){try{await screenshot('failure');console.error('STATE',JSON.stringify(await state()));}catch{}}
  await writeFile(new URL('browser-failure.json',artifacts),JSON.stringify({message:error.stack,results,errors,serverLog},null,2));process.exitCode=1;
} finally {await browser?.close();server.kill();}
